### ISSUE TITLE
强烈建议大家别买墙裂

### ISSUE THREAD

**Issue by nwf5d** [ldqk/new-pac#8]
上周六买了一年的服务，想下载个gdrive文件，只下载了3分钟，不到100M，现在就一直不可用的状态。
![image](https://user-images.githubusercontent.com/305404/80495365-658e1280-899a-11ea-8cec-ef6dd72a3535.png)

提了工单，刚开始还给回复
![image](https://user-images.githubusercontent.com/305404/80495669-cd445d80-899a-11ea-875c-e694ddd1cbd9.png)
按照回复未能解决，继续发了个工单，然后就是杳无音信了。
![image](https://user-images.githubusercontent.com/305404/80495835-ffee5600-899a-11ea-917b-749a3b8ecc68.png)
网站上也没有退款的渠道，所以强烈建议大家别买墙裂，其他的VPN估计也要慎重！

**Comment by ldqk** [comment]
墙裂不能用了？

**Comment by nwf5d** [comment]
> 墙裂不能用了？

反正我是不能用，其他人不清楚
